spring:
  application:
    name: backend
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce_db_inventory
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true

# Configuración de SpringDoc para integrar GraphQL en Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

# Configuración de Actuator para exponer métricas
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus" # Expone los endpoints health, info y prometheus
  metrics:
    export:
      prometheus:
        enabled: true # Habilita la exportación de métricas a Prometheus
